/*	simple Hello World, for cc65, for NES
 *  drawing a full screen from RLE, with rendering off
 *	using neslib
 *	Doug Fraker 2017
 */	


#include "neslib.h"
#include "MoreLib.c"

#include "Girl2.h" // our RLE compressed nametable data
// generated by NES Screen Tool, save nametable as RLE as .h file


const unsigned char palette[16]={ 

0x0f,0x17,0x27,0x36,0x0f,0x0b,0x0b,0x0b,0x0f,0x0f,0x0f,0x0b,0x0f,0x07,0x0b,0x0b };




	

void main (void) {
	
	// rendering is disabled at the startup
	
	// the init code set the palette brightness to
	// pal_bright(4); // normal
	
	//	load the palette
	pal_bg(palette);
		

	vram_adr(NAMETABLE_A);
	// this sets a start position on the BG, top left of screen
	
	vram_unrle(Girl2);
	// this unpacks a compressed full nametable
	
	// normally, I would set the scroll position, but the NMI code will automatically do that
	// since the RAM was zeroed on init, the X and Y scroll will still be 0,0
	
	//	turn on screen
	ppu_on_all();
	
	//	infinite loop
	while (1){
		
		// game code will go here.
		
	}
};
	
	